project_name: go-jsdelivr
env:
    - GO111MODULE=on
    - GOSUMDB=off
    - GOPROXY=https://goproxy.cn,direct
    - CGO_ENABLED=0
before:
    hooks:
        - go mod tidy
builds:
    -   id: go-jsdelivr
        ldflags:
            - -s -w
            - --extldflags "-static -fpic"
        gcflags:
            - -N -l
        flags:
            - -v
        main: ./cmd/jsdelivr.go
        binary: jsdelivr
        goos:
            - aix
            - darwin
            - dragonfly
            - freebsd
            - illumos
            - js
            - linux
            - solaris
            - windows
        goarch:
            - ppc64
            - 386
            - amd64
            - arm
            - arm64
            - wasm
            - ppc64le
            - mips
            - mipsle
            - mips64
            - mips64le
            - riscv64
            - s390x
        goarm:
            - 5
            - 6
            - 7
        gomips:
            - hardfloat
            - softfloat
checksum:
    name_template: "{{.ProjectName}}_{{ .Version }}_checksums.txt"
    algorithm: sha512
archives:
    -   format: tar.gz
        format_overrides:
            -   goos: windows
                format: zip
        name_template: "{{.ProjectName}}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
        replacements:
            amd64: 64bit
            386: 32bit
            arm: arm
            arm64: arm64
            darwin: macos
            linux: linux
            windows: windows
            openbsd: openbsd
            netbsd: netbsd
            freebsd: freebsd
            dragonfly: dragonflybsd
        files:
            - README.md
            - LICENSE
source:
    enabled: true
    name_template: '{{ .ProjectName }}_{{.Version}}'
changelog:
    skip: false
    sort: asc
    filters:
        exclude:
            - 'fix'
            - 'docker'
            - 'make'
            - 'tpl'
            - 'clash tpl'
            - 'config'
            - 'release'
            - 'upmod'
            - 'update'
            - 'start'
            - 'linit'
            - 'log'
            - 'go mod'
            - 'Makefile'
            - 'dockerfile'
            - 'gen'
            - '.release.'
            - 'rule'
            - 'build'
